// Throw

// Try... Catch

function sayMyName(name = ''){
  if(name === ''){
    throw new Error('Preenchimento obrigat√≥rio')
  }
  console.log('Depois do erro')
}
try {
  sayMyName()
} catch(e) {
  console.log(e)
}